### ISSUE TITLE
Not working on firefox (59+)

### ISSUE THREAD

**Issue by RussoNC** [katalon-studio/katalon-recorder-sample-plugin#2]
I have this error message : 
`Error: Syntax error, unrecognized expression: #external-exporter-bcd23515c3e854c4bac30d6a62e74f21b6327f66@temporary-addon-plain-text`

Tested in several computers with firefox 59+ and they are all having the same problem.

**Comment by RussoNC** [comment]
Well, after a lot of pain (I really needed it) **It works** !

### How ?
In order to use this little plugin, you need to do two things :
* Install Katalon Recoder addon [version 3.4.3](https://addons.mozilla.org/fr/firefox/addon/katalon-automation-record/versions/3.4.3)
* Take [this commit](https://github.com/katalon-studio/katalon-recorder-sample-plugin/commit/4617007bbb8e4a7f90e7c4ca246a1cd619422beb) (the first one) instead of the last version.

#### Why ?
My bet is that the Katalon devs didn't test the latest releases of their addon/plugin in firefox, assuming it would work. Can't blame them, it happens to everyone !

#### A few drawbacks with this approach
* You are using an older version of the addon
* You don't get the syntax color (xml,json,etc...).
I think this may be because we can't send (or the addon can't read) the other payload attribues besides content, like the extension and the mimetype.

This is just a temporary solution, waiting from an official fix from the devs. I hope this can help someone who's struggling like I did.

If someone find a more elegant way to doing this please let me know.

**Comment by teodesian** [comment]
Looks like the failure is due to not escaping @ in the relevant CSS selector.  Problem is on line 647 of katalon/kar.js in the katalon ide plugin.

Unfortunately there is no good way to fix this outside of the plugin.  Really what should be done is the plugin get forked and fixed, given this has been broken for nearly a whole year now.

**Comment by devalex88** [comment]
We are in the progress of making KR open-source. After that, formatter can be added directly into KR instead of writing plugins. I'll take a look at your bug report in the meantime.

https://forum.katalon.com/t/katalon-recorder-browser-extension-will-become-open-source/17769

**Comment by teodesian** [comment]
Super cool!  Thanks for looking into this.

**Comment by RussoNC** [comment]
> 
> 
> We are in the progress of making KR open-source. After that, formatter can be added directly into KR instead of writing plugins. I'll take a look at your bug report in the meantime.
> 
> https://forum.katalon.com/t/katalon-recorder-browser-extension-will-become-open-source/17769

Awesome ! Thanks

**Comment by devalex88** [comment]
The source code has been published.

https://forum.katalon.com/t/katalon-recorder-is-now-an-open-source-project/19466

**Comment by teodesian** [comment]
Thank you!
