### ISSUE TITLE
Please document all possible commands available to plugin authors

### ISSUE THREAD

**Issue by teodesian** [katalon-studio/katalon-recorder-sample-plugin#3]
I've got a request to build a formatter for the perl selenium extensions:
https://github.com/teodesian/Selenium-Remote-Driver/issues/415

The only straightforward way to make a formatter for, say, some other programming language's selenium extensions would involve creating a one-to-one mapping of katalon action -> lang action.

To build this as a dictionary or hash, I kind of need to know the possible commands that will come at me ahead of time.  Thing is, I don't see a real good list of that laying around anywhere.

I could make "Extension Scripts" to map all the actions possible, but that would sort of defeat the purpose of using a recorder, as custom scripts have always been a hacky manual process rather than the "point and click" experience which is the whole reason to use a recorder in the first place.

**Comment by teodesian** [comment]
Here's all the commands I know of right at the moment (and have mapped to my actions):
```
window.commandMap = { 
    "open": "$driver->get(",
    "click": "$driver->click(",
    "type": "$driver->send_keys(",
    "selectWindow": "$driver->switch_to_window("
};
```

**Comment by teodesian** [comment]
Hmm, would this happen to be the list of commands supported by the Selenium IDE, e.g.:

http://www.software-testing-tutorials-automation.com/2013/07/list-of-selenium-commands-with-examples.html

**Comment by teodesian** [comment]
One other thing.  I don't exactly see a way to load up custom formatters in the IDE plugin.

**Comment by teodesian** [comment]
Here's my stab at a plugin so far:

https://github.com/teodesian/Selenium-Remote-Driver/tree/katalon/katalon

I'm getting this error from the plugin debugger, and the formatter is just outputting java (I assume it's defaulting):

`Error: Syntax error, unrecognized expression: #external-exporter-5b31521861be420bec87659f5fb644a306e3eba5@temporary-addon-perlSRD`

**Comment by teodesian** [comment]
So, your plugin is definitely broken on firefox at least, looks like you are failing to properly escape the @ symbol in the ID you are generating here for the temporary plugin:

`
$("#external-exporter-5b31521861be420bec87659f5fb644a306e3eba5@temporary-addon-perlSRD");
Error: Syntax error, unrecognized expression: #external-exporter-5b31521861be420bec87659f5fb644a306e3eba5@temporary-addon-perlSRD`

`$("#external-exporter-5b31521861be420bec87659f5fb644a306e3eba5\\@temporary-addon-perlSRD");
Object { 0: option#external-exporter-5b31521861be420bec87659f5fb644a306e3eba5@temporary-addon-perlSRD.external-exporter
, length: 1, prevObject: Object(1) }
​`

I guess I need to open a bug over in that project to keep debugging this.

**Comment by teodesian** [comment]
Looks like the failure to escape is present in line 647 of katalon/kar.js in the katalon ide plugin.

I suppose I should figure out how to file a bug on that.

**Comment by teodesian** [comment]
Already filed here, looks like: https://github.com/katalon-studio/katalon-recorder-sample-plugin/issues/2

**Comment by devalex88** [comment]
The source code has been published.

https://forum.katalon.com/t/katalon-recorder-is-now-an-open-source-project/19466

**Comment by devalex88** [comment]
@teodesian,

Thank you so much for the bug report. Now the preferred method to add a new formatter is to contribute directly to KR. Please create a new issue if you need more information.

Samples:
* Implement New Relic Synthetics formatter katalon-studio/katalon-recorder#16
* Add protractor typescript template katalon-studio/katalon-recorder#23
